 * [tutorial1 1. Getting started]
 * [tutorial2 2. Customizing layout]
 * [tutorial3 3. Events]
 * [tutorial4 4. Workspaces]
 * [tutorial5 5. Extending VLDocking]
 * [tutorial6 6. Tips & Tricks]
 * [tutorial7 7. Heavyweight components]
 * [tutorial8 8. customizing the UI]
 * [tutorial9 9. Toolbars]
 * [tutorial10 10. Compound dockables]
 * [tutorial11 11. Multi-desktop applications]
 * [tutorial12 12. Anchors]
 